In [ ]:
#gamma(x, c) = [x1 from Ma, x2 from Ma, ..., xc from Ma]
#c = дата

In [1]:
import pandas as pd
import numpy as np

In [ ]:
class Actions:
    def __init__(self, actions_set):
        self.actions_set = actions_set
        self.counter = 0
    def remove_action(self, action):
        if action == 'В' and action == 'О':
            pass
        else:
            self.actions_set.remove(action)
    
    def return_available(self):
        
        return actions_set

In [11]:
a = 'Khakaton.xlsx'
app = pd.read_excel(a, sheet_name='График', )
employees = pd.DataFrame(app[:25])
drivers = pd.DataFrame(app[25:])
employees.head()

,дата,0,0.1,0.2,0.3,1,2,0.4,0.5,0.6,...,1.3,2.3,0.19,0.20,0.21,0.22,0.23,1.4,2.4,0.24
0,Сотрудник 1,2и,6и,8и,11и,15и,В,11и,8и,В,...,14и,19и,11и,11и,В,В,26и,14и,20и,8и
1,Сотрудник 2,8и,11и,11и,В,В,20и,8и,22и,8и,...,В,24и,5и,В,В,24и,8и,15и,55и,6и
2,Сотрудник 3,1и,1и,1и,8,В,19и,24и,26и,5и,...,В,В,22и,24и,9и,28и,В,В,19и,11и
3,Сотрудник 4,57и,57и,12и,В,В,24и,28и,В,В,...,28и,28и,В,22и,24и,5и,В,В,В,26и
4,Сотрудник 5,4и,28и,В,В,В,26и,В,В,В,...,В,В,8и,8и,7и,7и,24и,В,В,3и

In [12]:
drivers.head()

,дата,0,0.1,0.2,0.3,1,2,0.4,0.5,0.6,...,1.3,2.3,0.19,0.20,0.21,0.22,0.23,1.4,2.4,0.24
25,Водитель 1,1в,1в,6в,6в,В,В,В,26в,22в,...,22в,В,В,2в,2в,3в,8,В,В,1в
26,Водитель 2,25в,25в,25в,25в,В,В,25в,25в,25в,...,О,О,О,О,О,О,О,О,О,О
27,Водитель 3,10,11в,7в,8в,В,В,В,В,57в,...,В,В,12в,57в,57в,57в,12в,В,В,8
28,Водитель 4,В,57в,В,57в,12в,В,В,9в,В,...,В,В,3в,3в,11в,В,В,В,55в,26в
29,Водитель 5,7в,8в,В,В,10,В,26в,24в,7в,...,В,В,26в,22в,9в,26в,В,В,В,56в

In [13]:
drivers.columns = [drivers.columns[0]] + list(map(lambda x: str(x)[:1], list(drivers.columns)[1:]))
employees.columns = [employees.columns[0]] + list(map(lambda x: str(x)[:1], list(employees.columns)[1:]))

In [14]:
drivers.head()

,дата,0,0,0,0,1,2,0,0,0,...,1,2,0,0,0,0,0,1,2,0
25,Водитель 1,1в,1в,6в,6в,В,В,В,26в,22в,...,22в,В,В,2в,2в,3в,8,В,В,1в
26,Водитель 2,25в,25в,25в,25в,В,В,25в,25в,25в,...,О,О,О,О,О,О,О,О,О,О
27,Водитель 3,10,11в,7в,8в,В,В,В,В,57в,...,В,В,12в,57в,57в,57в,12в,В,В,8
28,Водитель 4,В,57в,В,57в,12в,В,В,9в,В,...,В,В,3в,3в,11в,В,В,В,55в,26в
29,Водитель 5,7в,8в,В,В,10,В,26в,24в,7в,...,В,В,26в,22в,9в,26в,В,В,В,56в

In [15]:
employees.head()

,дата,0,0,0,0,1,2,0,0,0,...,1,2,0,0,0,0,0,1,2,0
0,Сотрудник 1,2и,6и,8и,11и,15и,В,11и,8и,В,...,14и,19и,11и,11и,В,В,26и,14и,20и,8и
1,Сотрудник 2,8и,11и,11и,В,В,20и,8и,22и,8и,...,В,24и,5и,В,В,24и,8и,15и,55и,6и
2,Сотрудник 3,1и,1и,1и,8,В,19и,24и,26и,5и,...,В,В,22и,24и,9и,28и,В,В,19и,11и
3,Сотрудник 4,57и,57и,12и,В,В,24и,28и,В,В,...,28и,28и,В,22и,24и,5и,В,В,В,26и
4,Сотрудник 5,4и,28и,В,В,В,26и,В,В,В,...,В,В,8и,8и,7и,7и,24и,В,В,3и

# Eployees research

In [21]:
prev_days = employees.iloc[:, [1, 2, 3, 4, 5]]
prev_days.head()

     0    0    0    0    1
0   2и   6и   8и  11и  15и
1   8и  11и  11и    В    В
2   1и   1и   1и    8    В
3  57и  57и  12и    В    В
4   4и  28и    В    В    В